name: Test + Coveralls
on:
  push:
    branches:
      - dev
      - test/**
  pull_request:
    branches:
      - dev
      - test/**
  
jobs:
  test:
    name: Lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies (with cache)
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
        env:
          NODE_ENV: production

      - name: Test
        run: yarn test  --maxWorkers=2
  
  coverage:
    needs: test
    name: Build and Code Coverage on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Build
        run: yarn build
        
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
